spring.application.name=back-end
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=resume-builder
spring.ai.openai.api-key=x
spring.ai.openai.chat.base-url=http://localhost:11434
spring.ai.openai.chat.options.model=llama3.1
spring.ai.azure.openai.api-key=${AZURE_API_KEY}
spring.ai.azure.openai.endpoint=${AZURE_ENDPOINT}
spring.ai.azure.openai.chat.options.deployment-name=gpt-35-turbo-16k
spring.ai.azure.openai.chat.options.temperature=0.7
spring.data.mongodb.auto-index-creation=true