spring.application.name=back-end
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=resume-builder
spring.ai.openai.api-key=x
spring.ai.openai.chat.base-url=http://localhost:11434
spring.ai.openai.chat.options.model=llama3.1