import {Skeleton} from '@/components/ui/skeleton';

//! this page was completely generated by GitHub Copilot

export function LoadingResume() {
    return (
        <div className="flex w-full">
            {/* Sidebar Skeleton */}
            <div className="w-80 border-r p-4">
                <Skeleton className="mb-4 h-8 w-full" />
                <div className="space-y-2">
                    {Array.from({length: 4}).map((_, i) => (
                        <Skeleton key={i} className="h-10 w-full" />
                    ))}
                </div>
            </div>

            {/* Main Content */}
            <div className="flex-1 p-4 px-10">
                <div className="mb-4 flex justify-end gap-2">
                    <Skeleton className="h-10 w-10" />
                    <Skeleton className="h-10 w-10" />
                </div>

                <div className="w-full space-y-6 rounded-sm bg-white p-8">
                    {/* Name Section */}
                    <Skeleton className="h-12 w-3/4" />

                    {/* Contact Methods */}
                    <div className="mb-6 flex gap-4">
                        {Array.from({length: 3}).map((_, i) => (
                            <Skeleton key={i} className="h-8 w-40" />
                        ))}
                    </div>

                    {/* Sections (Education, Experience, Projects, Skills) */}
                    {Array.from({length: 4}).map((_, i) => (
                        <div key={i} className="space-y-4">
                            <Skeleton className="h-8 w-40" />
                            <div className="space-y-3">
                                {Array.from({length: 2}).map((_, j) => (
                                    <Skeleton key={j} className="h-24 w-full" />
                                ))}
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
}
